import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import NavBar from './NavBar'
import { Suspense } from 'react'
import { error } from 'console'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>
          {/* <Suspense fallback={<span>Loading...</span>}> */}
          {children}
          {/* </Suspense> */}
        </main>
      </body>
    </html>
  )
}
